# This file contains the default revive configuration.

ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule."lint/style/noBlankImport"]
[rule."lint/style/useContextAsFirstParam"]
[rule."lint/correctness/noContextKeysType"]
[rule."lint/style/noDotImport"]
[rule.empty-block]
[rule."lint/style/useErrorNaming"]
[rule."lint/style/useErrorLastReturn"]
[rule."lint/style/noErrorStrings"]
[rule."lint/style/useErrorf"]
[rule."lint/style/useExportedComment"]
[rule.increment-decrement]
[rule."lint/style/useIndentErrorFlow"]
[rule."lint/style/usePackageComments"]
[rule."lint/style/noRedundantRangeVal"]
[rule."lint/style/useReceiverNaming"]
[rule."lint/style/noSuperfluousElse"]
[rule."lint/style/useTimeNaming"]
[rule."lint/style/noUnexportedReturn"]
[rule."lint/style/noVarDeclaration"]
[rule."lint/style/useVarNaming"]
