version: "2"

linters:
  enable:
    - depguard
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: "github.com/sirupsen/logrus"
              desc: "use log/slog instead"
          allow:
            - $gostd
